# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notas.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bnotas.proto\x12\x05notas\"|\n\x0eSolicitudNotas\x12\r\n\x05nota1\x18\x01 \x01(\x02\x12\x13\n\x0bporcentaje1\x18\x02 \x01(\x02\x12\r\n\x05nota2\x18\x03 \x01(\x02\x12\x13\n\x0bporcentaje2\x18\x04 \x01(\x02\x12\r\n\x05nota3\x18\x05 \x01(\x02\x12\x13\n\x0bporcentaje3\x18\x06 \x01(\x02\"\'\n\x12RespuestaNotaFinal\x12\x11\n\tnotaFinal\x18\x01 \x01(\x02\x32W\n\x0cNotasService\x12G\n\x11\x43\x61lcularNotaFinal\x12\x15.notas.SolicitudNotas\x1a\x19.notas.RespuestaNotaFinal\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notas_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SOLICITUDNOTAS']._serialized_start=22
  _globals['_SOLICITUDNOTAS']._serialized_end=146
  _globals['_RESPUESTANOTAFINAL']._serialized_start=148
  _globals['_RESPUESTANOTAFINAL']._serialized_end=187
  _globals['_NOTASSERVICE']._serialized_start=189
  _globals['_NOTASSERVICE']._serialized_end=276
# @@protoc_insertion_point(module_scope)
